import = ["/home/victo/.config/alacritty/aura/aura-theme.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.92
blur = true
decorations = "None"

[window.padding]
x = 0
y = 0
